### ISSUE TITLE
inference No module named 'detectron2'

### ISSUE THREAD

**Issue by GISScience** [htcr/sam_road#19]
i am executing inference with your checkpoint --- but i am getting error

Google Colab Commands
%cd /content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/sam
!python /content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/inferencer.py --config /content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/config/toponet_vitb_256.yaml --output_dir /content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/output/

Error
/content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/sam
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/inferencer.py", line 10, in <module>
    from model import SAMRoad
  File "/content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/model.py", line 24, in <module>
    import vitdet
  File "/content/drive/MyDrive/Colab_Notebooks/htcr_sam/sam_road/vitdet.py", line 11, in <module>
    from detectron2.modeling import ViT
ModuleNotFoundError: No module named 'detectron2'

where i am doing mistake . 
please look at my shared colab here. 

https://drive.google.com/file/d/1IxdmtQ8VIAJ9kENeb5HJbTEloNzITncF/view?usp=sharing

is it true that minimum we need 30 gb RAM to use SAM_Road

**Comment by htcr** [comment]
Were you able to figure this out? I'm on travel right now but I can help take a look after getting back to my workstation.

**Comment by liweigis99** [comment]
@GISScience detectron2 needs to be installed following https://detectron2.readthedocs.io/tutorials/install.html

**Comment by GISScience** [comment]
Even after installing detectron2 , i am geeeting this error.. please help..
/content/drive/MyDrive/htcr_sam_road/sam_road
Traceback (most recent call last):
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/inferencer.py", line 247, in <module>
    net = SAMRoad(config)
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/model.py", line 363, in __init__
    new_state_dict = self.resize_sam_pos_embed(ckpt_state_dict, image_size, vit_patch_size, encoder_global_attn_indexes)
  File "/content/drive/MyDrive/htcr_sam_road/sam_road/model.py", line 385, in resize_sam_pos_embed
    pos_embed = new_state_dict['image_encoder.pos_embed']
KeyError: 'image_encoder.pos_embed'

**Comment by htcr** [comment]
Been quite busy recently - re your questions @GISScience:

1) detectron2 is only used for an ablation experiment which is not very important. I have removed it from the latest codebase. You should no longer see this problem.

2) As stated in README, inference should use the same config as training. so you should be using toponet_vitb_256_spacenet.yaml for spacenet_vitb_256_e10.ckpt. I ran python inferencer.py --config=config/toponet_vitb_256_spacenet.yaml --checkpoint=/home/congrui/Desktop/sam_road_repro/spacenet_vitb_256_e10.ckpt locally and did not see the issue you encountered.
