### ISSUE TITLE
error when running python inferencer.py

### ISSUE THREAD

**Issue by darld** [htcr/sam_road#25]
> Traceback (most recent call last):
  File "/home/ubuntu/sam_road/inferencer.py", line 279, in <module>
    pred_nodes, pred_edges, itsc_mask, road_mask = infer_one_img(net, img, config)
ValueError: not enough values to unpack (expected 4, got 2)

**Comment by ZC-peng** [comment]
Hello, I don't know if your problem has been solved. I noticed that you can proceed by skipping the processing of AOI_4_Shanghai_1597. Perhaps there's something wrong with the data in this one?

> > Traceback (most recent call last):
> > File "/home/ubuntu/sam_road/inferencer.py", line 279, in 
> > pred_nodes, pred_edges, itsc_mask, road_mask = infer_one_img(net, img, config)
> > ValueError: not enough values to unpack (expected 4, got 2)

**Comment by htcr** [comment]
Hi, there was a bug in inferencer.py when no vertex is detected. I have fixed that and you shall no longer see this issue.
